[package]
name = "monitoring_data"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.33.1"
pcap = "2.2.0"
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[lib]
crate-type = ["cdylib", "rlib"]